# 워크플로우 이름
name: Deploy to GitHub Pages
on: [push]
permissions:
  contents: write
# 실행할 작업 정의
jobs:
  build:
    # 최신 우분투 환경에서 실행
    runs-on: ubuntu-latest
    # 작업 단계 정의
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out